name: Deploy FortPolio App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build and Publish
      run: dotnet publish -c Release -o C:\Deploy\redisbysafi

    - name: Restart IIS
      run: |
        Restart-Service W3SVC
