name: Build and Deploy FortPolio App

on:
  push:
    branches:
      - master  # or whatever branch you deploy from

jobs:
  build-and-deploy:
    runs-on: self-hosted  # <--- very important!

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # ASP.NET Core 8.0
    - name: Extract Zip and Clean Up
      run: |
        $zipPath = 'C:\Users\Administrator\actions-runner\redisbysafi\Redis_Asp.net_Core_8\Redis_Asp.net_Core_8\05ee602b-eb8a-48aa-a778-90c5032d4f4e.zip'
        $extractPath = 'C:\Users\Administrator\actions-runner\redisbysafi\Redis_Asp.net_Core_8\Redis_Asp.net_Core_8\05ee602b-eb8a-48aa-a778-90c5032d4f4e'
        
        # Extract the ZIP file
        if (Test-Path $zipPath) {
            Expand-Archive -LiteralPath $zipPath -DestinationPath $extractPath -Force
        }

        # Clean up unwanted files (only if they exist)
        $folderToRemove = "$extractPath\infosafi-Redis_Asp.net_Core_8-90000ab\.github"
        if (Test-Path $folderToRemove) {
            Remove-Item -Path $folderToRemove -Force -Recurse
        } else {
            Write-Host "No .github folder found to remove"
        }

    - name: Publish the app
      run: |
        dotnet publish FortPolioApp.sln -c Release -o C:\Deploy\FortPolioApp

    - name: Restart IIS
      run: |
        Restart-Service W3SVC
