name: Deploy to Windows Server

on:
  push:
    branches:
      - master  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # for ASP.NET Core 8.0

    - name: Build the project
      run: dotnet publish -c Release -o publish_output

    - name: Deploy to Windows Server via WinRM
      uses: mmajcica/action-powershell-remoting@v2
      with:
        host: ${{ secrets.WINRM_HOST }}
        username: ${{ secrets.WINRM_USER }}
        password: ${{ secrets.WINRM_PASSWORD }}
        insecure: true  # set to false if you have proper SSL
        script: |
          # Create directory if doesn't exist
          if (!(Test-Path -Path "C:\Deploy\redisbysafi")) {
            New-Item -ItemType Directory -Path "C:\Deploy\redisbysafi"
          }
          # Copy files (you can use SMB, robocopy, or git pull inside server)
          # Here we'll assume simple git pull/update OR remote file copy setup
          
          # Example to restart IIS if needed
          Restart-Service -Name 'W3SVC'

