name: Build and Deploy FortPolio App

on:
  push:
    branches:
      - master  # or whatever branch you deploy from

jobs:
  build-and-deploy:
    runs-on: self-hosted  # <--- very important!

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # ASP.NET Core 8.0      

    - name: Publish the app
      run: |
        dotnet publish FortPolioApp.sln -c Release -o C:\Deploy\FortPolioApp

    - name: Restart IIS
      run: |
        Restart-Service W3SVC
